In [1]:
import pandas as pd
import numpy as np

# Import Data

In [2]:
df_master = pd.read_csv(r'E:\Dibimbing\Assignment Data Storytelling & Analysis\sample_superstore.csv', encoding='windows-1252')
df_before = df_master.copy()
df = df_master.copy()
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
print(f" Dimensi Dataset : {df.shape[0]:,} rows × {df.shape[1]} columns")

 Dimensi Dataset : 9,994 rows × 21 columns

In [4]:
print(f" Columns : {list(df.columns)}")

 Columns : ['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

# Data Cleaning

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [6]:
print('Jumlah duplikat data :', df.duplicated().sum())

Jumlah duplikat data : 0

In [7]:
(df.isnull().sum()).to_frame(name='Jumlah Missing Value')

               Jumlah Missing Value
Row ID                            0
Order ID                          0
Order Date                        0
Ship Date                         0
Ship Mode                         0
Customer ID                       0
Customer Name                     0
Segment                           0
Country                           0
City                              0
State                             0
Postal Code                       0
Region                            0
Product ID                        0
Category                          0
Sub-Category                      0
Product Name                      0
Sales                             0
Quantity                          0
Discount                          0
Profit                            0

In [8]:
((df.isnull().sum()/len(df))*100).to_frame(name='Persentase Missing Value')

               Persentase Missing Value
Row ID                              0.0
Order ID                            0.0
Order Date                          0.0
Ship Date                           0.0
Ship Mode                           0.0
Customer ID                         0.0
Customer Name                       0.0
Segment                             0.0
Country                             0.0
City                                0.0
State                               0.0
Postal Code                         0.0
Region                              0.0
Product ID                          0.0
Category                            0.0
Sub-Category                        0.0
Product Name                        0.0
Sales                               0.0
Quantity                            0.0
Discount                            0.0
Profit                              0.0

In [9]:
# Penyesuaian Tipe Data
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
df['Sales'] = pd.to_numeric(df['Sales'])
df['Quantity'] = pd.to_numeric(df['Quantity'])
df['Discount'] = pd.to_numeric(df['Discount'])
df['Profit'] = pd.to_numeric(df['Profit'])
df.dtypes

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code               int64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [10]:
# Format Teks & Kode Pos
df["Postal Code"] = df["Postal Code"].astype(str).str.split(".").str[0].str.zfill(5)

In [11]:
# Menghapus spasi berlebih
for c in df.select_dtypes(include=["object", "string"]).columns:
    df[c] = df[c].str.strip()

In [12]:
# Mencari Outlier
def find_outliers_iqr(dataframe, column):
    Q1 = dataframe[column].quantile(0.25) 
    Q3 = dataframe[column].quantile(0.75)
    IQR = Q3 - Q1
    
    batas_bawah = Q1 - 1.5 * IQR
    batas_atas = Q3 + 1.5 * IQR
    
    outliers = dataframe[(dataframe[column] < batas_bawah) | (dataframe[column] > batas_atas)]
    return outliers, batas_bawah, batas_atas

In [ ]:
# outlier pada kolom Profit
outliers_profit, lower_profit, upper_profit = find_outliers_iqr(df, 'Profit')

# outlier pada kolom Sales
outliers_sales, lower_sales, upper_sales = find_outliers_iqr(df, 'Sales')

print(f"Total baris data keseluruhan: {len(df)}")
print(f"Jumlah outlier pada Profit: {len(outliers_profit)} baris")
print(f"Batas normal Profit: {lower_profit:.2f} s/d {upper_profit:.2f}\n")

print(f"Jumlah outlier pada Sales: {len(outliers_sales)} baris")
print(f"Batas normal Sales: {lower_sales:.2f} s/d {upper_sales:.2f}")

Total baris data keseluruhan: 9994
Jumlah outlier pada Profit: 1881 baris
Batas normal Profit: -39.72 s/d 70.82

Jumlah outlier pada Sales: 1167 baris
Batas normal Sales: -271.71 s/d 498.93

Pertahankan outlier dikarenakan semua baris tersebut adalah transaksi yang valid

In [14]:
df.to_csv('final_superstore_cleaned.csv', index=False)